# Generated by Django 4.2.11 on 2026-02-25 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("TEMP", "Temperature Sensor"),
                            ("HUMIDITY", "Humidity Sensor"),
                            ("DOOR", "Door Sensor"),
                            ("PLUG", "Smart Plug"),
                            ("MOTION", "Motion Sensor"),
                            ("FRYER_OIL", "Fryer Oil Quality Sensor"),
                            ("WATER_LEAK", "Water Leak Sensor"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("LOW_BATTERY", "Low Battery"),
                            ("OFFLINE", "Offline"),
                            ("MAINTENANCE", "Maintenance"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("firmware_version", models.CharField(blank=True, max_length=50)),
                (
                    "zigbee_ieee_address",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("reporting_interval", models.IntegerField(default=300)),
                (
                    "temp_threshold_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "temp_threshold_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "oil_tpm_max_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fryer oil discard threshold (Total Polar Materials %). Default: 25.0",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "door_max_open_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Alert if door stays open longer than this many minutes. Default: 4",
                        null=True,
                    ),
                ),
                ("battery_percent", models.IntegerField(blank=True, null=True)),
                ("rssi", models.IntegerField(blank=True, null=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("installed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="restaurants.location",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "devices",
            },
        ),
        migrations.CreateModel(
            name="DeviceMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("BATTERY", "Battery Replacement"),
                            ("RELOCATE", "Relocation"),
                            ("FIRMWARE", "Firmware Update"),
                            ("REPAIR", "Repair"),
                            ("REPLACE", "Replacement"),
                            ("CALIBRATE", "Calibration"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("completed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_logs",
                        to="devices.device",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "device_maintenance",
                "ordering": ["-completed_at"],
            },
        ),
        migrations.CreateModel(
            name="DeviceCalibration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actual_temp", models.DecimalField(decimal_places=2, max_digits=5)),
                ("sensor_temp", models.DecimalField(decimal_places=2, max_digits=5)),
                ("offset", models.DecimalField(decimal_places=2, max_digits=5)),
                ("notes", models.TextField(blank=True)),
                ("calibrated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "calibrated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calibrations",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "db_table": "device_calibrations",
                "ordering": ["-calibrated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["device_id"], name="devices_device__c4b5e4_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["restaurant", "status"], name="devices_restaur_cdb726_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["location"], name="devices_locatio_71ae1b_idx"),
        ),
    ]
