# Generated by Django 4.2.11 on 2026-02-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="co2_max_ppm",
            field=models.IntegerField(
                blank=True,
                help_text="Alert threshold for CO₂ concentration (ppm). Default: 1500",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="humidity_max_rh",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum acceptable relative humidity (%). Alert if above.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="humidity_min_rh",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum acceptable relative humidity (%). Alert if below.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="device_type",
            field=models.CharField(
                choices=[
                    ("TEMP", "Temperature Sensor"),
                    ("HUMIDITY", "Humidity Sensor"),
                    ("DOOR", "Door Sensor"),
                    ("PLUG", "Smart Plug"),
                    ("MOTION", "Motion Sensor"),
                    ("FRYER_OIL", "Fryer Oil Quality Sensor"),
                    ("WATER_LEAK", "Water Leak Sensor"),
                    ("CO2", "CO₂ / IAQ Sensor"),
                    ("HVAC", "HVAC / Refrigeration Monitor"),
                ],
                max_length=20,
            ),
        ),
    ]
