# Generated by Django 4.2.11 on 2026-02-25 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("fda", "FDA"),
                            ("usda_fsis", "USDA FSIS"),
                            ("cdc", "CDC"),
                            ("manual", "Manual Entry"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="ID from source system (e.g. FDA recall number)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("reason", models.TextField()),
                (
                    "hazard_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Salmonella', 'Listeria', 'Foreign material', 'Undeclared allergen'",
                        max_length=100,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("I", "Class I — Serious health hazard"),
                            (
                                "II",
                                "Class II — May cause temporary adverse health consequences",
                            ),
                            (
                                "III",
                                "Class III — Unlikely to cause adverse health consequences",
                            ),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("terminated", "Terminated"),
                            ("ongoing", "Ongoing"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("recalling_firm", models.CharField(max_length=300)),
                ("firm_city", models.CharField(blank=True, max_length=100)),
                ("firm_state", models.CharField(blank=True, max_length=50)),
                ("firm_country", models.CharField(default="US", max_length=50)),
                (
                    "distribution_pattern",
                    models.TextField(
                        blank=True,
                        help_text="Narrative description of distribution area",
                    ),
                ),
                (
                    "affected_states",
                    models.JSONField(
                        default=list, help_text="List of two-letter state codes"
                    ),
                ),
                ("recall_initiation_date", models.DateField(blank=True, null=True)),
                ("center_classification_date", models.DateField(blank=True, null=True)),
                ("termination_date", models.DateField(blank=True, null=True)),
                ("voluntary_mandated", models.CharField(blank=True, max_length=50)),
                (
                    "initial_firm_notification",
                    models.CharField(blank=True, max_length=200),
                ),
                ("product_quantity", models.CharField(blank=True, max_length=200)),
                ("raw_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "recalls",
                "ordering": ["-recall_initiation_date"],
            },
        ),
        migrations.CreateModel(
            name="RecallProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_description", models.TextField()),
                ("brand_name", models.CharField(blank=True, max_length=200)),
                (
                    "upc_codes",
                    models.JSONField(default=list, help_text="List of UPC/GTIN codes"),
                ),
                ("lot_numbers", models.JSONField(default=list)),
                (
                    "best_by_dates",
                    models.JSONField(default=list, help_text="List of date strings"),
                ),
                (
                    "package_sizes",
                    models.JSONField(default=list, help_text="e.g. ['12 oz', '1 lb']"),
                ),
                (
                    "code_info",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable lot/date code instructions",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="recalls.recall",
                    ),
                ),
            ],
            options={
                "db_table": "recall_products",
            },
        ),
        migrations.CreateModel(
            name="RecallAcknowledgment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("acknowledged", "Acknowledged"),
                            ("not_affected", "Not affected"),
                            ("remediated", "Product removed/returned"),
                            ("escalated", "Escalated to health dept"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("remediation_date", models.DateTimeField(blank=True, null=True)),
                ("units_removed", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acknowledgments",
                        to="recalls.recall",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recall_acknowledgments",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "recall_acknowledgments",
            },
        ),
        migrations.AddIndex(
            model_name="recall",
            index=models.Index(
                fields=["source", "external_id"], name="recalls_source_0080a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recall",
            index=models.Index(fields=["status"], name="recalls_status_fa456f_idx"),
        ),
        migrations.AddIndex(
            model_name="recall",
            index=models.Index(
                fields=["hazard_type"], name="recalls_hazard__7fbe50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recall",
            index=models.Index(
                fields=["recall_initiation_date"], name="recalls_recall__89207f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recallacknowledgment",
            index=models.Index(fields=["status"], name="recall_ackn_status_9e66ec_idx"),
        ),
        migrations.AddIndex(
            model_name="recallacknowledgment",
            index=models.Index(
                fields=["recall", "status"], name="recall_ackn_recall__a87dce_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recallacknowledgment",
            unique_together={("recall", "restaurant")},
        ),
    ]
