# Generated by Django 4.2.11 on 2026-02-25 03:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID from the health department source system",
                        max_length=200,
                    ),
                ),
                (
                    "source_jurisdiction",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'LA County', 'NYC DOHMH', 'CA CDPH'",
                        max_length=100,
                    ),
                ),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("routine", "Routine"),
                            ("follow_up", "Follow-up"),
                            ("complaint", "Complaint-driven"),
                            ("pre_opening", "Pre-opening"),
                            ("reinspection", "Re-inspection"),
                            ("special", "Special"),
                        ],
                        default="routine",
                        max_length=20,
                    ),
                ),
                ("inspected_at", models.DateTimeField()),
                (
                    "inspector_id",
                    models.CharField(
                        blank=True,
                        help_text="Anonymized or redacted inspector identifier",
                        max_length=100,
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("P", "Pending"),
                            ("X", "Closed"),
                        ],
                        max_length=2,
                    ),
                ),
                ("passed", models.BooleanField(blank=True, null=True)),
                ("closed", models.BooleanField(default=False)),
                ("closure_reason", models.TextField(blank=True)),
                ("reopened_at", models.DateTimeField(blank=True, null=True)),
                ("report_url", models.URLField(blank=True)),
                ("raw_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "inspections",
                "ordering": ["-inspected_at"],
            },
        ),
        migrations.CreateModel(
            name="InspectionViolation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("serious", "Serious"),
                            ("minor", "Minor"),
                            ("observation", "Observation"),
                        ],
                        default="minor",
                        max_length=20,
                    ),
                ),
                (
                    "violation_status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("corrected_on_site", "Corrected on site"),
                            ("not_corrected", "Not corrected"),
                            ("repeat", "Repeat violation"),
                        ],
                        default="observed",
                        max_length=25,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Temperature control', 'Personnel hygiene', 'Food storage', 'Pest control'",
                        max_length=100,
                    ),
                ),
                ("location_description", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("corrective_action", models.TextField(blank=True)),
                ("points_deducted", models.IntegerField(blank=True, null=True)),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="inspections.inspection",
                    ),
                ),
            ],
            options={
                "db_table": "inspection_violations",
                "indexes": [
                    models.Index(
                        fields=["inspection", "severity"],
                        name="inspection__inspect_3d4ffa_idx",
                    ),
                    models.Index(fields=["code"], name="inspection__code_f7bf31_idx"),
                    models.Index(
                        fields=["category"], name="inspection__categor_0ccc93_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InspectionSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField(blank=True, null=True)),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("routine", "Routine"),
                            ("follow_up", "Follow-up"),
                            ("complaint", "Complaint-driven"),
                            ("pre_opening", "Pre-opening"),
                            ("reinspection", "Re-inspection"),
                            ("special", "Special"),
                        ],
                        default="routine",
                        max_length=20,
                    ),
                ),
                ("assigned_inspector_id", models.CharField(blank=True, max_length=100)),
                ("jurisdiction", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("missed", "Missed"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_inspection",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule",
                        to="inspections.inspection",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection_schedules",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "inspection_schedules",
                "ordering": ["scheduled_date"],
                "indexes": [
                    models.Index(
                        fields=["scheduled_date"], name="inspection__schedul_1d5a70_idx"
                    ),
                    models.Index(
                        fields=["restaurant", "status"],
                        name="inspection__restaur_73dab6_idx",
                    ),
                    models.Index(
                        fields=["status"], name="inspection__status_03d9c2_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="inspection",
            index=models.Index(
                fields=["restaurant", "-inspected_at"],
                name="inspections_restaur_318bba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inspection",
            index=models.Index(fields=["grade"], name="inspections_grade_ea3245_idx"),
        ),
        migrations.AddIndex(
            model_name="inspection",
            index=models.Index(
                fields=["inspected_at"], name="inspections_inspect_724c17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inspection",
            index=models.Index(
                fields=["source_jurisdiction"], name="inspections_source__df927b_idx"
            ),
        ),
    ]
