"""Analytics models for compliance insights"""

from django.db import models
from apps.restaurants.models import Restaurant, Organization


class ComplianceReport(models.Model):
    """Generated compliance reports"""

    class ReportType(models.TextChoices):
        DAILY = 'DAILY', 'Daily Summary'
        WEEKLY = 'WEEKLY', 'Weekly Summary'
        MONTHLY = 'MONTHLY', 'Monthly Summary'
        INSPECTION_PREP = 'INSPECTION_PREP', 'Inspection Preparation'

    class ReportStatus(models.TextChoices):
        GENERATING = 'GENERATING', 'Generating'
        COMPLETED = 'COMPLETED', 'Completed'
        FAILED = 'FAILED', 'Failed'

    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, related_name='reports')
    report_type = models.CharField(max_length=20, choices=ReportType.choices)
    status = models.CharField(max_length=20, choices=ReportStatus.choices, default=ReportStatus.GENERATING)

    # Report period
    period_start = models.DateField()
    period_end = models.DateField()

    # Report data (computed fields)
    compliance_score = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    total_readings = models.IntegerField(default=0)
    violation_count = models.IntegerField(default=0)
    critical_alert_count = models.IntegerField(default=0)

    # Report file
    report_url = models.URLField(blank=True)

    # Generated by
    generated_by = models.ForeignKey('accounts.User', on_delete=models.SET_NULL, null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'compliance_reports'
        indexes = [
            models.Index(fields=['restaurant', '-created_at']),
            models.Index(fields=['report_type', 'period_start']),
        ]

    def __str__(self):
        return f"{self.restaurant.name} - {self.report_type} ({self.period_start} to {self.period_end})"


class InspectionPrediction(models.Model):
    """AI-powered health inspection predictions"""

    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, related_name='predictions')

    # Prediction data
    predicted_inspection_date = models.DateField()
    predicted_score = models.IntegerField(null=True, blank=True)
    confidence = models.DecimalField(max_digits=5, decimal_places=2)  # 0-100

    # Risk factors
    risk_factors = models.JSONField(default=list)  # List of identified risks
    recommendations = models.JSONField(default=list)  # List of recommendations

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'inspection_predictions'
        ordering = ['predicted_inspection_date']

    def __str__(self):
        return f"{self.restaurant.name} - Prediction: {self.predicted_inspection_date}"


class MetricSnapshot(models.Model):
    """Daily snapshots of key metrics for analytics"""

    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, related_name='metric_snapshots')
    date = models.DateField()

    # Device metrics
    active_devices = models.IntegerField(default=0)
    offline_devices = models.IntegerField(default=0)
    low_battery_devices = models.IntegerField(default=0)

    # Reading metrics
    total_readings = models.IntegerField(default=0)
    avg_temperature = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    min_temperature = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    max_temperature = models.DecimalField(max_digits=6, decimal_places=2, null=True)

    # Alert metrics
    total_alerts = models.IntegerField(default=0)
    critical_alerts = models.IntegerField(default=0)
    warning_alerts = models.IntegerField(default=0)

    # Compliance metrics
    compliance_score = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    violations_resolved = models.IntegerField(default=0)
    violations_active = models.IntegerField(default=0)

    # Manual logs
    manual_logs = models.IntegerField(default=0)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'metric_snapshots'
        unique_together = ['restaurant', 'date']
        indexes = [
            models.Index(fields=['restaurant', '-date']),
        ]

    def __str__(self):
        return f"{self.restaurant.name} - {self.date}"
