# Generated by Django 4.2.11 on 2026-02-25 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("accounts", "0001_initial"),
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantaccess",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="restaurants.restaurant"
            ),
        ),
        migrations.AddField(
            model_name="restaurantaccess",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="pushtoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="push_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="password_reset_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mfasettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mfa_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="backupcode",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="backup_codes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_keys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to="restaurants.organization",
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="restaurants.organization",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="restaurants",
            field=models.ManyToManyField(
                related_name="users",
                through="accounts.RestaurantAccess",
                to="restaurants.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddIndex(
            model_name="trusteddevice",
            index=models.Index(
                fields=["user", "is_active"], name="trusted_dev_user_id_02eb40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trusteddevice",
            index=models.Index(fields=["token"], name="trusted_dev_token_7dc9b7_idx"),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["user", "-created_at"], name="user_sessio_user_id_35bce9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["session_key", "is_active"],
                name="user_sessio_session_b2102c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["expires_at"], name="user_sessio_expires_66ae96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="restaurantaccess",
            index=models.Index(
                fields=["user", "restaurant"], name="restaurant__user_id_e945cd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="restaurantaccess",
            unique_together={("user", "restaurant")},
        ),
        migrations.AddIndex(
            model_name="pushtoken",
            index=models.Index(
                fields=["user", "is_active"], name="push_tokens_user_id_3067f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pushtoken",
            index=models.Index(fields=["token"], name="push_tokens_token_c43621_idx"),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["token", "expires_at"], name="password_re_token_9adc88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["user", "-created_at"], name="password_re_user_id_fcb0eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="backupcode",
            index=models.Index(
                fields=["user", "is_used"], name="backup_code_user_id_07fbaf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(
                fields=["user", "is_active"], name="api_keys_user_id_6e7352_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(
                fields=["organization", "is_active"], name="api_keys_organiz_70e45b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(fields=["key_hash"], name="api_keys_key_has_8f2f29_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["organization"], name="users_organiz_ca9165_idx"
            ),
        ),
    ]
