# Generated by Django 4.2.11 on 2026-02-27 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthDeptRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("org_name", models.CharField(max_length=255)),
                (
                    "jurisdiction",
                    models.CharField(
                        help_text="e.g. 'Cook County, IL' or 'State of Oregon'",
                        max_length=100,
                    ),
                ),
                (
                    "jurisdiction_state",
                    models.CharField(help_text="2-letter US state code", max_length=2),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="How does your department plan to use the platform?",
                    ),
                ),
                (
                    "estimated_restaurants",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Approximate number of food establishments in your jurisdiction",
                        null=True,
                    ),
                ),
                ("contact_name", models.CharField(max_length=255)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PROVISIONED", "Provisioned"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant_slug",
                    models.SlugField(
                        blank=True,
                        help_text="Auto-derived from org_name on approval",
                        max_length=60,
                    ),
                ),
                ("provisioned_at", models.DateTimeField(blank=True, null=True)),
                ("submitter_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hd_registrations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="hd_registra_status_d63659_idx",
                    ),
                    models.Index(
                        fields=["contact_email"], name="hd_registra_contact_1c658f_idx"
                    ),
                ],
            },
        ),
    ]
