# Generated by Django 4.2.11 on 2026-02-25 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily Summary"),
                            ("WEEKLY", "Weekly Summary"),
                            ("MONTHLY", "Monthly Summary"),
                            ("QUARTERLY", "Quarterly Summary"),
                            ("INSPECTION_PREP", "Inspection Preparation"),
                            ("SCORECARD", "Scorecard"),
                            ("CUSTOM", "Custom Report"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("GENERATING", "Generating"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "compliance_score",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("total_readings", models.IntegerField(default=0)),
                ("violation_count", models.IntegerField(default=0)),
                ("critical_alert_count", models.IntegerField(default=0)),
                (
                    "avg_temperature",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("report_url", models.URLField(blank=True, max_length=500)),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("file_pages", models.IntegerField(default=0)),
                ("email_recipients", models.JSONField(default=list)),
                ("email_sent", models.BooleanField(default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_reports",
                        to="restaurants.organization",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "compliance_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportDeliveryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("WEBHOOK", "Webhook"),
                            ("DOWNLOAD", "Manual Download"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("recipient_phone", models.CharField(blank=True, max_length=50)),
                ("sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("opened", models.BooleanField(default=False)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_logs",
                        to="reports.compliancereport",
                    ),
                ),
            ],
            options={
                "db_table": "report_delivery_logs",
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("INSPECTION_SUMMARY", "Inspection Summary"),
                            ("COMPLIANCE_AUDIT", "Compliance Audit"),
                            ("VIOLATION_ANALYSIS", "Violation Analysis"),
                            ("TREND_REPORT", "Trend Report"),
                            ("CUSTOM", "Custom Template"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("template_structure", models.JSONField(default=dict)),
                ("include_sections", models.JSONField(default=list)),
                ("custom_logo_url", models.URLField(blank=True)),
                ("custom_colors", models.JSONField(default=dict)),
                ("is_approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_templates",
                        to="restaurants.organization",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "report templates",
                "db_table": "report_templates",
                "indexes": [
                    models.Index(
                        fields=["organization", "is_approved"],
                        name="report_temp_organiz_e2336e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily Summary"),
                            ("WEEKLY", "Weekly Summary"),
                            ("MONTHLY", "Monthly Summary"),
                            ("QUARTERLY", "Quarterly Summary"),
                            ("INSPECTION_PREP", "Inspection Preparation"),
                            ("SCORECARD", "Scorecard"),
                            ("CUSTOM", "Custom Report"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("BI_WEEKLY", "Every 2 Weeks"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("email_recipients", models.JSONField(default=list)),
                ("include_readings", models.BooleanField(default=True)),
                ("include_alerts", models.BooleanField(default=True)),
                ("include_predictions", models.BooleanField(default=False)),
                ("include_recommendations", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_schedules",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "report schedules",
                "db_table": "report_schedules",
                "indexes": [
                    models.Index(
                        fields=["restaurant", "is_active"],
                        name="report_sche_restaur_eefbad_idx",
                    ),
                    models.Index(
                        fields=["next_run_at"], name="report_sche_next_ru_b183af_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="compliancereport",
            index=models.Index(
                fields=["restaurant", "-created_at"],
                name="compliance__restaur_506910_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="compliancereport",
            index=models.Index(
                fields=["report_type", "-created_at"],
                name="compliance__report__86af4a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="compliancereport",
            index=models.Index(fields=["status"], name="compliance__status_dd1ef5_idx"),
        ),
        migrations.AddIndex(
            model_name="compliancereport",
            index=models.Index(
                fields=["period_start", "period_end"],
                name="compliance__period__9a6cd0_idx",
            ),
        ),
    ]
