# Generated by Django 4.2.11 on 2026-02-25 03:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("TEMPERATURE_LOG", "Temperature Log"),
                            ("COOLING_LOG", "Cooling Log"),
                            ("COOKING_LOG", "Cooking Log"),
                            ("HOT_HOLDING", "Hot Holding"),
                            ("COLD_HOLDING", "Cold Holding"),
                            ("DATE_MARKING", "Date Marking"),
                            ("SANITIZATION", "Sanitization"),
                            ("PEST_CONTROL", "Pest Control"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("passed", models.BooleanField(default=True)),
                ("corrective_action", models.TextField(blank=True)),
                ("photo_url", models.URLField(blank=True)),
                ("checked_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "compliance_checks",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("WALK_IN_COOLER", "Walk-in Cooler"),
                            ("WALK_IN_FREEZER", "Walk-in Freezer"),
                            ("REACH_IN_COOLER", "Reach-in Cooler"),
                            ("REACH_IN_FREEZER", "Reach-in Freezer"),
                            ("HOT_HOLDING", "Hot Holding"),
                            ("DRY_STORAGE", "Dry Storage"),
                            ("PREP_AREA", "Prep Area"),
                            ("COOKING_LINE", "Cooking Line"),
                            ("DISHWASHING", "Dishwashing"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("temp_min_f", models.DecimalField(decimal_places=2, max_digits=5)),
                ("temp_max_f", models.DecimalField(decimal_places=2, max_digits=5)),
                ("description", models.TextField(blank=True)),
                ("position", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "locations",
                "db_table": "locations",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("STARTER", "Starter"),
                            ("PROFESSIONAL", "Professional"),
                            ("ENTERPRISE", "Enterprise"),
                        ],
                        default="STARTER",
                        max_length=20,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("logo_url", models.URLField(blank=True)),
                (
                    "subscription_status",
                    models.CharField(default="active", max_length=20),
                ),
                (
                    "monthly_fee",
                    models.DecimalField(decimal_places=2, default=99.0, max_digits=10),
                ),
                ("last_inspection_date", models.DateField(blank=True, null=True)),
                ("last_inspection_score", models.IntegerField(blank=True, null=True)),
                (
                    "compliance_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "organizations",
            },
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=50)),
                ("zip_code", models.CharField(max_length=20)),
                ("country", models.CharField(default="USA", max_length=50)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("cuisine_type", models.CharField(blank=True, max_length=100)),
                ("seating_capacity", models.IntegerField(blank=True, null=True)),
                ("square_footage", models.IntegerField(blank=True, null=True)),
                ("health_department_id", models.CharField(blank=True, max_length=100)),
                ("last_inspection_date", models.DateField(blank=True, null=True)),
                (
                    "last_inspection_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "compliance_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("gateway_id", models.CharField(max_length=100, unique=True)),
                ("gateway_last_seen", models.DateTimeField(blank=True, null=True)),
                ("gateway_version", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("CLOSED", "Closed"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurants",
                        to="restaurants.organization",
                    ),
                ),
            ],
            options={
                "db_table": "restaurants",
            },
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["name"], name="organizatio_name_5cd1d4_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["subscription_status"], name="organizatio_subscri_72b760_idx"
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="restaurants.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="compliancecheck",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="restaurants.location",
            ),
        ),
        migrations.AddField(
            model_name="compliancecheck",
            name="performed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="compliancecheck",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compliance_checks",
                to="restaurants.restaurant",
            ),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["organization", "name"], name="restaurants_organiz_829f8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["gateway_id"], name="restaurants_gateway_21ebb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(fields=["status"], name="restaurants_status_7a5ebb_idx"),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["city", "state"], name="restaurants_city_84531f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["restaurant", "location_type"],
                name="locations_restaur_a0e814_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="compliancecheck",
            index=models.Index(
                fields=["restaurant", "checked_at"],
                name="compliance__restaur_2163bb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="compliancecheck",
            index=models.Index(
                fields=["check_type"], name="compliance__check_t_1e7fd5_idx"
            ),
        ),
    ]
