# Generated by Django 4.2.11 on 2026-02-25 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemperatureLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("temperature", models.DecimalField(decimal_places=2, max_digits=6)),
                ("logged_at", models.DateTimeField()),
                ("food_item", models.CharField(blank=True, max_length=255)),
                ("corrective_action", models.TextField(blank=True)),
                ("in_safe_range", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="devices.device",
                    ),
                ),
                (
                    "logged_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "temperature_logs",
                "ordering": ["-logged_at"],
                "indexes": [
                    models.Index(
                        fields=["restaurant", "-logged_at"],
                        name="temperature_restaur_d66342_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "humidity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "pressure",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("door_open", models.BooleanField(blank=True, null=True)),
                ("door_open_seconds", models.IntegerField(blank=True, null=True)),
                (
                    "power_usage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "energy_consumed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "oil_tpm_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total Polar Materials percentage (0–100)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "oil_temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fryer oil temperature (°F)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "water_detected",
                    models.BooleanField(
                        blank=True,
                        help_text="True = water detected by the sensor probe",
                        null=True,
                    ),
                ),
                ("battery_percent", models.IntegerField(blank=True, null=True)),
                ("rssi", models.IntegerField(blank=True, null=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "db_table": "sensor_readings",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "-timestamp"],
                        name="sensor_read_device__bae3ac_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="sensor_read_timesta_56e803_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SensorAggregate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aggregate_type",
                    models.CharField(
                        choices=[
                            ("HOURLY", "Hourly"),
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("temp_avg", models.DecimalField(decimal_places=2, max_digits=6)),
                ("temp_min", models.DecimalField(decimal_places=2, max_digits=6)),
                ("temp_max", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "humidity_avg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "humidity_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "humidity_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("reading_count", models.IntegerField()),
                ("violation_count", models.IntegerField(default=0)),
                (
                    "oil_tpm_avg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "oil_tpm_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("oil_tpm_readings", models.IntegerField(default=0)),
                (
                    "door_open_events",
                    models.IntegerField(
                        default=0,
                        help_text="Number of distinct open events in this period",
                    ),
                ),
                (
                    "max_door_open_seconds",
                    models.IntegerField(
                        blank=True,
                        help_text="Longest single door-open event duration (seconds)",
                        null=True,
                    ),
                ),
                (
                    "water_events",
                    models.IntegerField(
                        default=0, help_text="Number of wet detections in this period"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aggregates",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "db_table": "sensor_aggregates",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "-timestamp"],
                        name="sensor_aggr_device__5b2288_idx",
                    )
                ],
                "unique_together": {("device", "aggregate_type", "timestamp")},
            },
        ),
    ]
