# Generated by Django 4.2.11 on 2026-02-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensoraggregate",
            name="co2_avg",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sensoraggregate",
            name="co2_high_events",
            field=models.IntegerField(
                default=0,
                help_text="Number of readings that exceeded the CO₂ threshold",
            ),
        ),
        migrations.AddField(
            model_name="sensoraggregate",
            name="co2_max",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sensoraggregate",
            name="hvac_fault_events",
            field=models.IntegerField(
                default=0, help_text="Number of fault-state readings in this period"
            ),
        ),
        migrations.AddField(
            model_name="sensorreading",
            name="co2_ppm",
            field=models.IntegerField(
                blank=True,
                help_text="CO₂ concentration in parts-per-million",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sensorreading",
            name="hvac_fault_code",
            field=models.CharField(
                blank=True,
                help_text="Vendor fault code reported by the unit (e.g. E4, F3)",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sensorreading",
            name="hvac_state",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
