# Generated by Django 4.2.11 on 2026-02-25 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("TEMP_VIOLATION", "Temperature Violation"),
                            ("HUMIDITY_VIOLATION", "Humidity Violation"),
                            ("DOOR_OPEN", "Door Open Too Long"),
                            ("LOW_BATTERY", "Low Battery"),
                            ("DEVICE_OFFLINE", "Device Offline"),
                            ("MANUAL_LOG", "Manual Log Required"),
                            ("FRYER_OIL", "Fryer Oil Quality Alert"),
                            ("WATER_LEAK", "Water Leak Detected"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("WARNING", "Warning"),
                            ("INFO", "Info"),
                        ],
                        default="WARNING",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("RESOLVED", "Resolved"),
                            ("FALSE_POSITIVE", "False Positive"),
                        ],
                        default="ACTIVE",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "threshold_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "threshold_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("notification_sent", models.BooleanField(default=False)),
                ("notification_sent_at", models.DateTimeField(blank=True, null=True)),
                ("notification_methods", models.JSONField(default=list)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledgement_notes", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="devices.device",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("PUSH", "Push Notification"),
                            ("WEBHOOK", "Webhook"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recipient", models.CharField(max_length=255)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("external_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="alerts.alert",
                    ),
                ),
            ],
            options={
                "db_table": "notification_logs",
            },
        ),
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("TEMP_THRESHOLD", "Temperature Threshold"),
                            ("HUMIDITY_THRESHOLD", "Humidity Threshold"),
                            ("DOOR_DURATION", "Door Open Duration"),
                            ("DEVICE_OFFLINE", "Device Offline"),
                            ("BATTERY_LOW", "Battery Low"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("WARNING", "Warning"),
                            ("INFO", "Info"),
                        ],
                        default="WARNING",
                        max_length=20,
                    ),
                ),
                ("parameters", models.JSONField(default=dict)),
                ("enabled", models.BooleanField(default=True)),
                ("notification_methods", models.JSONField(default=list)),
                ("notification_delay_minutes", models.IntegerField(default=0)),
                ("escalation_enabled", models.BooleanField(default=False)),
                ("escalation_delay_minutes", models.IntegerField(default=30)),
                (
                    "escalation_severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("WARNING", "Warning"),
                            ("INFO", "Info"),
                        ],
                        default="CRITICAL",
                        max_length=20,
                    ),
                ),
                ("active_all_day", models.BooleanField(default=True)),
                ("active_start_time", models.TimeField(blank=True, null=True)),
                ("active_end_time", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to="devices.device",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "alert rules",
                "db_table": "alert_rules",
            },
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["restaurant", "-created_at"], name="alerts_restaur_e035d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["status", "severity"], name="alerts_status_5203b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(fields=["alert_type"], name="alerts_alert_t_eda531_idx"),
        ),
    ]
