# Generated by Django 4.2.11 on 2026-02-25 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("predicted_inspection_date", models.DateField()),
                ("predicted_score", models.IntegerField(blank=True, null=True)),
                ("confidence", models.DecimalField(decimal_places=2, max_digits=5)),
                ("risk_factors", models.JSONField(default=list)),
                ("recommendations", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "inspection_predictions",
                "ordering": ["predicted_inspection_date"],
            },
        ),
        migrations.CreateModel(
            name="MetricSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("active_devices", models.IntegerField(default=0)),
                ("offline_devices", models.IntegerField(default=0)),
                ("low_battery_devices", models.IntegerField(default=0)),
                ("total_readings", models.IntegerField(default=0)),
                (
                    "avg_temperature",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "min_temperature",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "max_temperature",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                ("total_alerts", models.IntegerField(default=0)),
                ("critical_alerts", models.IntegerField(default=0)),
                ("warning_alerts", models.IntegerField(default=0)),
                (
                    "compliance_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("violations_resolved", models.IntegerField(default=0)),
                ("violations_active", models.IntegerField(default=0)),
                ("manual_logs", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_snapshots",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "metric_snapshots",
                "indexes": [
                    models.Index(
                        fields=["restaurant", "-date"],
                        name="metric_snap_restaur_a6b26a_idx",
                    )
                ],
                "unique_together": {("restaurant", "date")},
            },
        ),
        migrations.CreateModel(
            name="ComplianceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily Summary"),
                            ("WEEKLY", "Weekly Summary"),
                            ("MONTHLY", "Monthly Summary"),
                            ("INSPECTION_PREP", "Inspection Preparation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("GENERATING", "Generating"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="GENERATING",
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "compliance_score",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("total_readings", models.IntegerField(default=0)),
                ("violation_count", models.IntegerField(default=0)),
                ("critical_alert_count", models.IntegerField(default=0)),
                ("report_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_reports",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_compliance_reports",
                "indexes": [
                    models.Index(
                        fields=["restaurant", "-created_at"],
                        name="analytics_c_restaur_2f3c9e_idx",
                    ),
                    models.Index(
                        fields=["report_type", "period_start"],
                        name="analytics_c_report__1ab27d_idx",
                    ),
                ],
            },
        ),
    ]
