# Generated by Django 4.2.11 on 2026-02-25 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTAManifest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=50, unique=True)),
                ("release_date", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField()),
                ("docker_images", models.JSONField(default=dict)),
                ("config_changes", models.JSONField(default=list)),
                ("migrations", models.JSONField(default=list)),
                ("pre_update_hooks", models.JSONField(default=list)),
                ("post_update_hooks", models.JSONField(default=list)),
                ("rollback_commands", models.JSONField(default=list)),
                ("min_gateway_version", models.CharField(max_length=50)),
                ("max_gateway_version", models.CharField(max_length=50)),
                ("critical", models.BooleanField(default=False)),
                ("rollback_safe", models.BooleanField(default=True)),
                ("requires_reboot", models.BooleanField(default=False)),
                ("manifest_url", models.URLField(blank=True)),
                ("signature_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("TESTING", "Testing"),
                            ("STAGED", "Staged"),
                            ("ROLLING_OUT", "Rolling Out"),
                            ("COMPLETED", "Completed"),
                            ("ROLLED_BACK", "Rolled Back"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("rollout_percentage", models.IntegerField(default=0)),
                ("auto_approve", models.BooleanField(default=False)),
                ("total_gateways", models.IntegerField(default=0)),
                ("updated_gateways", models.IntegerField(default=0)),
                ("failed_gateways", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ota_manifests",
                "ordering": ["-release_date"],
                "indexes": [
                    models.Index(
                        fields=["version"], name="ota_manifes_version_a37223_idx"
                    ),
                    models.Index(
                        fields=["status"], name="ota_manifes_status_701ffa_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GatewayUpdateStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gateway_id", models.CharField(max_length=100)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DOWNLOADING", "Downloading"),
                            ("VERIFYING", "Verifying"),
                            ("BACKING_UP", "Backing Up"),
                            ("APPLYING", "Applying"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("ROLLED_BACK", "Rolled Back"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("current_step", models.CharField(blank=True, max_length=100)),
                ("progress_percentage", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("backup_created", models.BooleanField(default=False)),
                ("backup_location", models.CharField(blank=True, max_length=255)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                ("update_log", models.TextField(blank=True)),
                (
                    "manifest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gateway_statuses",
                        to="ota.otamanifest",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "gateway_update_status",
                "indexes": [
                    models.Index(
                        fields=["gateway_id", "state"],
                        name="gateway_upd_gateway_6e29bc_idx",
                    ),
                    models.Index(fields=["state"], name="gateway_upd_state_192864_idx"),
                    models.Index(
                        fields=["started_at"], name="gateway_upd_started_0da82a_idx"
                    ),
                ],
                "unique_together": {("gateway_id", "manifest")},
            },
        ),
        migrations.CreateModel(
            name="GatewayBackup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gateway_id", models.CharField(max_length=100)),
                ("backup_path", models.CharField(max_length=255)),
                ("version", models.CharField(max_length=50)),
                ("size_bytes", models.BigIntegerField()),
                ("includes_database", models.BooleanField(default=True)),
                ("includes_config", models.BooleanField(default=True)),
                ("includes_docker_images", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("keep_until", models.DateTimeField(blank=True, null=True)),
                ("is_cleaned_up", models.BooleanField(default=False)),
                (
                    "manifest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backups",
                        to="ota.otamanifest",
                    ),
                ),
            ],
            options={
                "db_table": "gateway_backups",
                "indexes": [
                    models.Index(
                        fields=["gateway_id", "created_at"],
                        name="gateway_bac_gateway_2724f5_idx",
                    ),
                    models.Index(
                        fields=["keep_until"], name="gateway_bac_keep_un_b25965_idx"
                    ),
                ],
            },
        ),
    ]
