# Generated by Django 4.2.11 on 2026-02-25 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recalls", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportingInstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("ed", "Emergency Department"),
                            ("urgent_care", "Urgent Care"),
                            ("primary_care", "Primary Care"),
                            ("lab", "Laboratory"),
                            ("hospital", "Hospital"),
                            ("public_health", "Public Health Agency"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("jurisdiction", models.CharField(blank=True, max_length=100)),
                ("geohash", models.CharField(blank=True, max_length=5)),
                ("state", models.CharField(blank=True, max_length=2)),
                (
                    "api_key_hash",
                    models.CharField(
                        help_text="HMAC of the institution's API key",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "clinical_institutions",
            },
        ),
        migrations.CreateModel(
            name="OutbreakInvestigation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("active", "Active investigation"),
                            ("closed", "Closed"),
                            ("archived", "Archived"),
                        ],
                        default="open",
                        max_length=15,
                    ),
                ),
                ("pathogen", models.CharField(blank=True, max_length=200)),
                ("suspected_vehicle", models.TextField(blank=True)),
                ("geographic_scope", models.CharField(blank=True, max_length=200)),
                ("cluster_start_date", models.DateField(blank=True, null=True)),
                ("cluster_end_date", models.DateField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("case_count_at_open", models.IntegerField(default=0)),
                (
                    "auto_generated",
                    models.BooleanField(
                        default=False,
                        help_text="True if created automatically by the clustering engine",
                    ),
                ),
                (
                    "cluster_score",
                    models.FloatField(
                        blank=True,
                        help_text="Composite score from the clustering algorithm",
                        null=True,
                    ),
                ),
                (
                    "lead_investigator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "clinical_investigations",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="ClinicalCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_hash",
                    models.CharField(
                        db_index=True,
                        help_text="HMAC of source patient identifier (see privacy app)",
                        max_length=64,
                    ),
                ),
                ("age_range", models.CharField(blank=True, max_length=10)),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other/Unknown"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "geohash",
                    models.CharField(
                        blank=True,
                        help_text="Precision-5 geohash of patient's general area",
                        max_length=5,
                    ),
                ),
                ("zip3", models.CharField(blank=True, max_length=3)),
                (
                    "illness_status",
                    models.CharField(
                        choices=[
                            ("suspected", "Suspected"),
                            ("confirmed", "Confirmed"),
                            ("ruled_out", "Ruled out"),
                        ],
                        default="suspected",
                        max_length=15,
                    ),
                ),
                ("onset_date", models.DateField(blank=True, null=True)),
                ("illness_duration_days", models.IntegerField(blank=True, null=True)),
                (
                    "symptoms",
                    models.JSONField(
                        default=list,
                        help_text="List of symptom strings, e.g. ['diarrhea', 'vomiting', 'fever']",
                    ),
                ),
                ("stool_culture_collected", models.BooleanField(blank=True, null=True)),
                ("pathogen", models.CharField(blank=True, max_length=200)),
                ("serotype", models.CharField(blank=True, max_length=100)),
                (
                    "lab_reference",
                    models.CharField(
                        blank=True,
                        help_text="De-identified lab reference number (not the actual accession number)",
                        max_length=100,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("recovered", "Recovered"),
                            ("hospitalized", "Hospitalized"),
                            ("ongoing", "Ongoing"),
                            ("deceased", "Deceased"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=15,
                    ),
                ),
                ("hospitalized", models.BooleanField(blank=True, null=True)),
                ("icu_admission", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "investigation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cases",
                        to="clinical.outbreakinvestigation",
                    ),
                ),
                (
                    "reporting_institution",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cases",
                        to="clinical.reportinginstitution",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "clinical_cases",
                "ordering": ["-onset_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClinicalExposure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exposure_type",
                    models.CharField(
                        choices=[
                            ("restaurant", "Restaurant / Food service"),
                            ("grocery", "Grocery / Retail food"),
                            ("home", "Home-prepared food"),
                            ("catered", "Catered event"),
                            ("water", "Water source"),
                            ("animal", "Animal contact"),
                            ("person", "Person-to-person"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                ("exposure_date", models.DateField(blank=True, null=True)),
                ("geohash", models.CharField(blank=True, max_length=6)),
                (
                    "establishment_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Fast food', 'Full-service restaurant', 'Deli'",
                        max_length=100,
                    ),
                ),
                (
                    "food_items",
                    models.JSONField(
                        default=list,
                        help_text="List of food item descriptions — strip brand names before storing",
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exposures",
                        to="clinical.clinicalcase",
                    ),
                ),
                (
                    "linked_recall",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinical_exposures",
                        to="recalls.recall",
                    ),
                ),
            ],
            options={
                "db_table": "clinical_exposures",
                "indexes": [
                    models.Index(
                        fields=["exposure_type", "exposure_date"],
                        name="clinical_ex_exposur_61dbcc_idx",
                    ),
                    models.Index(
                        fields=["geohash"], name="clinical_ex_geohash_011fef_idx"
                    ),
                    models.Index(
                        fields=["linked_recall"], name="clinical_ex_linked__3ce819_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="clinicalcase",
            index=models.Index(
                fields=["onset_date"], name="clinical_ca_onset_d_fff9d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalcase",
            index=models.Index(
                fields=["pathogen"], name="clinical_ca_pathoge_423965_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalcase",
            index=models.Index(
                fields=["geohash"], name="clinical_ca_geohash_32c24e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalcase",
            index=models.Index(
                fields=["illness_status"], name="clinical_ca_illness_64609b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalcase",
            index=models.Index(
                fields=["investigation"], name="clinical_ca_investi_38865a_idx"
            ),
        ),
    ]
