# Generated by Django 4.2.11 on 2026-02-25 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "source_system",
                    models.CharField(
                        choices=[
                            ("clinical", "Clinical / EHR"),
                            ("retail", "Retail Loyalty"),
                            ("consumer", "Consumer App"),
                            ("restaurant", "Restaurant Staff"),
                        ],
                        max_length=20,
                    ),
                ),
                ("age_range", models.CharField(blank=True, max_length=10)),
                ("zip3", models.CharField(blank=True, max_length=3)),
                ("geohash", models.CharField(blank=True, max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "privacy_data_subjects",
                "indexes": [
                    models.Index(
                        fields=["source_system"], name="privacy_dat_source__5bf95d_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DataProcessingAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("read", "Read"),
                            ("write", "Write"),
                            ("delete", "Delete"),
                            ("export", "Export"),
                            ("anonymize", "Anonymize"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "data_categories",
                    models.JSONField(
                        default=list,
                        help_text="List of data category labels accessed, e.g. ['health', 'location']",
                    ),
                ),
                ("purpose", models.CharField(max_length=200)),
                ("performed_by_system", models.CharField(blank=True, max_length=100)),
                ("endpoint", models.CharField(blank=True, max_length=255)),
                (
                    "record_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'ClinicalCase', 'SensorReading'",
                        max_length=100,
                    ),
                ),
                ("record_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="privacy.datasubject",
                    ),
                ),
            ],
            options={
                "db_table": "privacy_audit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["subject", "-created_at"],
                        name="privacy_aud_subject_a76db2_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="privacy_aud_action_d77b9b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("inspection_public", "Public inspection data sharing"),
                            ("iot_monitoring", "IoT sensor monitoring"),
                            ("clinical_reporting", "Clinical case reporting"),
                            ("recall_matching", "Recall and exposure matching"),
                            ("analytics_aggregated", "Aggregated analytics"),
                            ("analytics_individual", "Individual-level analytics"),
                            ("data_export", "Data export to third parties"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("granted", "Granted"),
                            ("revoked", "Revoked"),
                            ("pending", "Pending"),
                        ],
                        max_length=10,
                    ),
                ),
                ("recorded_by_system", models.CharField(blank=True, max_length=100)),
                (
                    "legal_basis",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'consent', 'public_interest', 'vital_interests'",
                        max_length=60,
                    ),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True,
                        help_text="HMAC of IP address, for audit only",
                        max_length=64,
                    ),
                ),
                ("user_agent_hash", models.CharField(blank=True, max_length=64)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_records",
                        to="privacy.datasubject",
                    ),
                ),
            ],
            options={
                "db_table": "privacy_consent_records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["subject", "scope", "-created_at"],
                        name="privacy_con_subject_f9a17c_idx",
                    )
                ],
            },
        ),
    ]
